config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', profiles: 'users/profiles' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blog_posts#index'

  resources :blog_posts, only: [:show, :new, :create, :edit, :update, :destroy] do
    get 'pinit', on: :member
    get 'unpin', on: :member
    get 'show_all', on: :collection
  end

  resources :images, only: [:create, :destroy]

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy] do
    get 'index_posts', on: :member
  end

  resources :archives, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations


  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 200 }
  validates :content, presence: true, length: { minimum: 30 }

  def sticky?
    sticky_order != 100
  end

  def pinit!
    self.sticky_order = 1
    self.save
  end

  def unpin!
    self.sticky_order = 100
    self.save
  end

  def published?
    published == 1
  end

end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :blog_post
  belongs_to :category, counter_cache: :blog_post_count
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :categorizations, dependent: :destroy
  has_many :blog_posts, through: :categorizations

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/image.rb
class Image < ApplicationRecord
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blog_posts

  enum level: {member: 0, admin: 1}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController

  def index
    @posts = BlogPost.order(created_at: :desc)
    @posts_by_month = @posts.group_by { |p| p.created_at.beginning_of_month }
  end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :show_all]

  def index
    if params[:search]
      @posts = BlogPost.where('title like ?', "%#{params[:search]}%")
    else
      @posts = BlogPost.order(sticky_order: :asc).order(id: :desc)
    end
    @posts = @posts.paginate( per_page: 4, page: params[:page] )
  end

  def show
    @post = BlogPost.friendly.find(params[:id])
    @categories = @post.categories 
  end

  def new
    @post = BlogPost.new
    @maximum_length = BlogPost.validators_on( :description ).second.options[:maximum]
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @post = BlogPost.new(resource_params)
    @post.user = current_user

    if params[:submit_publish]
      @post.published = 1
    else
      @post.published = 0
    end

    if @post.save
      if @post.published?
        flash[:notice] = 'Your post successfully published!'
        render 'new'
      else
        flash[:notice] = 'Save as draft success! your post will hide from public'
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @post = BlogPost.friendly.find(params[:id])
    @maximum_length = BlogPost.validators_on( :description ).second.options[:maximum]
    @categories = Category.all
  end

  def update
    @post = BlogPost.friendly.find(params[:id])
    @categories = Category.all

    if params[:submit_publish]
      @post.published = 1
    else
      @post.published = 0
    end

    if @post.update(resource_params)
      if @post.published?
        flash[:notice] = 'Your post successfully updated!'
        render 'edit'
      else
        flash[:notice] = 'Save as draft success! your post will hide from public'
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def destroy
    @post = BlogPost.friendly.find(params[:id])
    @post.destroy
    redirect_to request.referrer
  end
  
  # my Custom method
  def pinit
    @post = BlogPost.friendly.find(params[:id])
    @post.pinit!
    redirect_to root_path
  end

  def unpin
    @post = BlogPost.friendly.find(params[:id])
    @post.unpin!
    redirect_to root_path
  end

  def show_all 
    @posts = BlogPost.order(id: :desc)
    @posts = @posts.paginate( per_page: 10, page: params[:page] )
  end

  # strong params
  private

  def resource_params
    params.require(:blog_post).permit(:title, :description, :content, :published, :category_ids => [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :index_posts]

  def index
    @categories = Category.all
    @category = Category.new
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @category = Category.new(resources_params)
    
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.friendly.find(params[:id])
  end

  def update
    @category = Category.friendly.find(params[:id])
    if @category.update(resources_params)
      redirect_to categories_path
    else
      render 'edit'
    end

  end

  def destroy 
    @category = Category.friendly.find(params[:id])
    if @category.destroy
      redirect_to categories_path
    else
      flash[:notice] = 'Something wrong'
    end
    
  end

  def index_posts
    @category = Category.friendly.find(params[:id])
    @index_posts = @category.blog_posts.order(id: :desc).paginate( per_page: 5, page: params[:page] )
  end

  private

  def resources_params
    params.require(:category).permit(:name)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  protect_from_forgery except: :create
  def create
    @image = Image.new(image_params)
    @image.save
 
    respond_to do |format|
      format.json { render :json => { url: Refile.attachment_url(@image, :image), image_id: @image.image_id } }
    end
  end
 
  def destroy
    @image = Image.find_by(image_id: params[:id])
    @image.destroy
    respond_to do |format|
      format.json { render :json => { status: :ok } }
    end
  end
  
  private
 
  def image_params
    params.require(:image).permit(:image)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!

  def new
    if user_signed_in? 
      if current_user.admin?
        super
      else
        redirect_to new_user_session_path 
      end
    else
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/archives/index.html.erb
<div class='form-group'>
  <div>
    <h2><i class="fab fa-firstdraft"></i> Archives</h2>

    <% @posts_by_month.sort.reverse.each do | month, posts | %>
      <h3><%= month.strftime('%B %Y') %></h3>
      <ul>
        <% posts.sort.each do | post | %>
          <li><%= link_to post.title, blog_post_path(post), target: '_blank' %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

<% @title = 'Archives' %>
<% @description = 'Blog Archives' %>

app/views/blog_posts/_form.html.erb
<% if @post.errors.any? %>
  <div class='alert alert-danger alert-dismissable' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
    <% @post.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
    <% end %>
  </div>
<% end %>

<%= form_for @post do |p| %>
<div class='form-group'>
  <%= p.label :title %>
  <%= p.text_field :title, class: 'form-control' %>
</div>

<div class='form-group'>
  <%= p.label :description %>
  <%= p.text_area :description, maxlength: @maximum_length, id: 'description', class: 'form-control', rows: '5' %>
  Characters left: <span id="counter" data-maximum-length="<%= @maximum_length %>"><%= @maximum_length %></span>
</div>

<div class='form-group'> 
  <%= p.label :content %>
  <%= p.text_area :content, class: 'form-control', 'data-provider': :summernote %>
</div>

<div class='form-group'>
  Category : 
  <% @categories.each do |c| %>
    <%= check_box_tag c.id, c.id, @post.categories.include?(c), name: 'blog_post[category_ids][]' %>
    <%= label_tag c.id, c.name %>
  <% end %> 
</div>

<div class='form-group'>
  <%= p.submit 'Publish', name: 'submit_publish', class: 'btn btn-primary' %>
  <%= p.submit 'Draft', name: 'submit_draft', class: 'btn btn-info' %>
</div>
<% end %>

<script>
    $(document).ready(function() {
      var description = $("#description");
      var counter     = $("#counter");
      var maximum_length  = counter.data("maximum-length");

      description.keyup(function() {
          counter.text(maximum_length - $(this).val().length);
      });

    });
</script>

app/views/blog_posts/_show_post.html.erb
<div class="post">
    <div class="title">
      <h2><%= @post.title.titleize %></h2>
    </div>

    <div class="meta">
      <%= @post.created_at.strftime("%d %B %Y") %> oleh <%= @post.user.name %>
    </div>

    <div class="content">
      <%=raw @post.content %>
        <div>Category :
          <% @categories.each do |c| %>
            <span class='label label-primary'><%= link_to c.name, index_posts_category_path(c), style: 'color:white' %></span>
          <% end %>
        </div>
    </div>

    <% if user_signed_in? %>
      <div class="edit">
        <%= link_to 'Edit this post', edit_blog_post_path %> | <%= link_to 'Delete post', blog_post_path(@post), data: {confirm: 'Are you sure permanent delete this post?'}, method: :delete %>
      </div>
    <% end %>
</div>

<div id="disqus_thread"></div>
<script>

var disqus_config = function () {
this.page.url = <%= request.domain %><%= url_for(@posts) %>;
this.page.identifier = <%= @post.id %>;
};
(function() { 
var d = document, s = d.createElement('script');
s.src = 'https://papooa.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/blog_posts/edit.html.erb
<%= render 'form' %>

app/views/blog_posts/index.html.erb
<div class="post">
  
<% if @posts.any? %>
  <% @posts.each do |p| %>
    <div class="title">
      <% if p.published? %>
        <h2><%= link_to p.title.titleize, blog_post_path(p), class: 'text-warning' %> 
        <% if p.sticky? %>
          <span class="glyphicon glyphicon-pushpin"></span>
        <% end %>
        </h2>
    </div>


    <div class="meta">
      <%= p.created_at.strftime("%d %B %Y") %> by <%= p.user.name %>
    </div>

    <div class="content">
      <p><%= truncate(sanitize(p.content, tags: []), length: 500) %></p>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Edit Post', edit_blog_post_path(p) %> |
          <%= link_to 'Delete Post', blog_post_path(p), method: :delete, data: {confirm: 'Are you sure?'} %> |
        <% if p.sticky? %>
          <%= link_to 'Unpin', unpin_blog_post_path(p) %>
        <% else %>
            <%= link_to 'Pin it', pinit_blog_post_path(p) %>
          <% end %>
        <% end %>
    </div>

      <% end %>

  <% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

<% else %>

  <div>
    <h2>Oopss... no post found :( <i class="fab fa-earlybirds"></i></h2>
  </div>

<% end %>

</div>

<% @blog_title = 'Papooa' %>
<% @description = 'Just personal blog' %>

app/views/blog_posts/new.html.erb
<%= render 'form' %>

app/views/blog_posts/show.html.erb
<% if @post.published? %>
  <%= render 'show_post' %>
<% elsif %>
  <% user_signed_in? %>
  <div>
    <h2><i class="fab fa-firstdraft"> This is Draft Post, only visible for Admin</i></h2>
  </div>
    <%= render 'show_post' %>
<% else %>
  <div>
    <h2>Oopss... no post found <i class="fab fa-earlybirds"></i></h2>
  </div>
<% end %>

<% @title = @post.title %>
<% @description = @post.description %>

app/views/blog_posts/show_all.html.erb
<div>
  <%= link_to 'Add New', new_blog_post_path, class: 'btn btn-primary' %>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Status</th>
        <th>Created at</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do | post | %>
        <tr>
          <td><%= link_to post.title, blog_post_path(post), target: '_blank' %></td>
          <td><%= raw(post.categories.map{ |c| raw(link_to(c.name, index_posts_category_path(c))) }.join(', ')) %></td>
          <td><%= post.published? ? "Published" : "Draft" %></td>
          <td><%= post.created_at.strftime("%d %B %Y") %></td>
          <td><%= link_to '', edit_blog_post_path(post), class: 'far fa-edit' %> | <%= link_to '', blog_post_path(post), class: 'fas fa-trash', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/categories/edit.html.erb
<% if @category.errors.any? %>
  <div class='alert alert-danger alert-dismissable' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
    <% @category.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
    <% end %>
  </div>
<% end %>

<%= form_for @category do |c| %>
  <div class='form-group'>
    <%= c.label :Category_Name %>
    <%= c.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= c.submit 'Add', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<% if @category.errors.any? %>
  <div class='alert alert-danger alert-dismissable' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      <% @category.errors.full_messages.each do |error| %>
        <div>
          <%= error %>
        </div>
      <% end %>
  </div>
<% end %>

<%= form_for @category do |c| %>
  <% if user_signed_in? %>
    <div class='form-group'>
      <%= c.label :Category_Name %>
      <%= c.text_field :name, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= c.submit 'Add', class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

<div class='form-group'>
  <div>
    <h2><i class="fas fa-clipboard-list"></i> Blog Categories</h2>
    <% @categories.each do | c | %>
      <div>
        <%= link_to c.name, index_posts_category_path(c) %> (<%= c.blog_post_count %>) 
        <% if user_signed_in? %>
           <%= link_to 'Delete', category_path(c), method: :delete, data: { confirm: 'Are you sure?' } %> <%= link_to 'Edit', edit_category_path(c) %>
         <% end %>
      </div>
    <% end %>
  </div>
</div>

<% @title = 'Categories' %>
<% @description = 'Categories' %>

app/views/categories/index_posts.html.erb
<div class="post">
  
<% if @index_posts.any? %>
  <div>
    <h3>All Posts for Category: <%= @category.name %></h3>
  </div>

  <% @index_posts.each do |p| %>
    <% if p.published? %>
      <div class="title">
        <h2><%= link_to p.title.titleize, blog_post_path(p), class: 'text-warning' %></h2>
      </div>

      <div class="meta">
        <%= p.created_at.strftime("%d %B %Y") %> by <%= p.user.name %>
      </div>

      <div class="content">
        <p><%= truncate(sanitize(p.content, tags: []), length: 500) %></p>
          <% if user_signed_in? %>
            <%= link_to 'Edit Post', edit_blog_post_path(p) %> |
            <%= link_to 'Delete Post', blog_post_path(p), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
      </div>

    <% elsif user_signed_in? %>

      <div class="title">
        <h2><i class="fab fa-firstdraft"></i> [DRAFT] <%= link_to p.title.titleize, blog_post_path(p), class: 'text-warning' %></h2>
      </div>

      <div class="meta">
        <%= p.created_at.strftime("%d %B %Y") %> by <%= p.user.name %>
      </div>

      <div class="content">
        <p><%= truncate(sanitize(p.content, tags: []), length: 500) %></p>
          <% if user_signed_in? %>
            <%= link_to 'Edit Post', edit_blog_post_path(p) %> |
            <%= link_to 'Delete Post', blog_post_path(p), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
      </div>
    <% end %>
  <% end %>

<%= will_paginate @index_posts, renderer: BootstrapPagination::Rails %>

<% else %>

  <div>
    <h2>Oopss... no post found <i class="fab fa-earlybirds"></i></h2>
  </div>

<% end %>

</div>

<% @title = "Category #{@category.name}" %>
<% @description = "Category #{@category.name}" %>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <div class='alert alert-danger alert-dismissable' role='alert'>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
    <% @category.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
    <% end %>
  </div>
<% end %>

<%= form_for @category do |c| %>
  <div class='form-group'>
    <%= c.label :Category_Name %>
    <%= c.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= c.submit 'Add', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar transparent navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Papooa', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar">
      <%= form_tag root_path, method: :get, class: 'navbar-form navbar-left' do %>
              <div class='form-group'>
                      <%= text_field_tag :search, nil, class: 'form-control' %>
              </div>
              <div class='form-group'>
                      <%= submit_tag 'Search', class: 'btn btn-default' %>
              </div>
      <% end %>	

      <% if user_signed_in? %>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Halo, <%= current_user.name %>  <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </ul>
        </li>
      </ul>
    <% end %>

        <ul class="nav navbar-nav navbar-left" id="navbar">
          <li><%= link_to 'Categories', categories_path %></li>
          <li><%= link_to 'Archives', archives_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools  <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="https://ocr.papooa.com" target="_blank">Image2Text</a></li>
            </ul>
          </li>
          <% if user_signed_in? %>
            <li><%= link_to 'Post', show_all_blog_posts_path %></li>
          <% end %>
          <li><a href="https://github.com/bueuk/" target="_blank"><i class="fab fa-github"> GitHub</i></a></li>
        </ul>
			</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || @blog_title %></title>
    <meta charset="UTF-8">
    <meta property="og:title" content="<%= @title || @blog_title %>">
    <meta property="og:description" content="<%= @description || 'Papooa' %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <!-- Fixed navbar -->
      <div class="container" >
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <% end %>
        <%= yield %>
      </div>
  </body>
</html>